# Generated by Django 5.0.3 on 2024-11-22 14:16

from django.db import migrations
from allauth.account.models import EmailAddress
from allauth.account.utils import user_email

class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_article_options"),
    ]

    def verify_superuser(apps, schema_editor):
        from django.contrib.auth import get_user_model

        User = get_user_model()
        superuser = User.objects.get(email="admin@gmail.com")

        email, created = EmailAddress.objects.get_or_create(
            user=superuser, email=user_email(superuser)
        )
        email.verified = True
        email.save()

    operations = [migrations.RunPython(verify_superuser)]
